tracer:
  property: "I AM THE Default"
spring:
  jpa:
    database: "MYSQL"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    platform: "mysql"
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/eagle_eye_local?=true&characterEncoding=utf8&useSSL=false"
    username: "demo"
    password: "demo123"
    dbcp2:
      validation-query: "select 1"