server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-service

  cloud:
    config:
      server:
        #本地文件配置
        bootstrap: true
        native:
          search-locations: file:///Users/yaomalang/Repositories/Exercises/config-repo/config/licensingservice

        #Git远程服务配置
  #        git:
  #          uri: https://gitee.com/wenyongfan/config-repo.git
  #          search-paths: /config/licensingservice
  #          username: jackyfane@gmail.com
  #          password: jacky123
  #          default-label: master